[package]
name = "megaeth-gas-estimator"
version = "0.1.0"
edition = "2024"

[dependencies]
ethers = "2.0"
tokio = { version = "1", features = ["full"] }
clap = { version = "4.0", features = ["derive"] }
